/************************************************************************
 *    This file was generated by eTPU Graphical Configuration Tool        
 *                                                                        
 *    DO NOT EDIT !!! DO NOT EDIT !!! DO NOT EDIT !!! DO NOT EDIT !!!     
 *                                                                        
 *  DESCRIPTION:
 *  This file is generated together with the same name .c file.
 *  It contains function prototypes and useful defines.
 *
 *  Creation Date:  07/01/2011 8:22:58 
 *
 **************************************************************************/

/**************************************************************************
 * general macros
 **************************************************************************/
#define FS_ETPU_TCR1_PRESCALER(x)    (((x)-1) & 0xFF)
#define FS_ETPU_TCR2_PRESCALER(x)    ((((x)-1) & 0x3F)<<16)
#define FS_ETPU_TCR1_STAC_SRVSLOT(x) (((x) & 0xF)<<16)
#define FS_ETPU_TCR2_STAC_SRVSLOT(x) ((x) & 0xF)
#define FS_ETPU_CHANNEL_FUNCTION(x)  ((x) & 0x1F)
#define FS_ETPU_CHANNEL_PARAMS(x)    ((x) & 0x7F)
#define FS_ETPU_FUNCTION_MODE(x)     ((x) & 0x3)

#define FS_ETPU_ENTRY_TABLE_ADDR     (((FS_ETPU_ENTRY_TABLE)>>11) & 0x1F)

#define FS_ETPU_FUNCTION_MODE_00     FS_ETPU_FUNCTION_MODE(0)
#define FS_ETPU_FUNCTION_MODE_01     FS_ETPU_FUNCTION_MODE(1)
#define FS_ETPU_FUNCTION_MODE_10     FS_ETPU_FUNCTION_MODE(2)
#define FS_ETPU_FUNCTION_MODE_11     FS_ETPU_FUNCTION_MODE(3)

#define FS_ETPU_HSR_0                (0)
#define FS_ETPU_HSR_1                (1)
#define FS_ETPU_HSR_2                (2)
#define FS_ETPU_HSR_3                (3)
#define FS_ETPU_HSR_4                (4)
#define FS_ETPU_HSR_5                (5)
#define FS_ETPU_HSR_6                (6)
#define FS_ETPU_HSR_7                (7)

#define ETPU_ENGINE_A_CHANNEL(x)  (x)
#define ETPU_ENGINE_B_CHANNEL(x)  ((x)+64)
#define ETPU_CHAN_NOT_USED        (-1)

/**************************************************************************
 * define functions to channels
 **************************************************************************/
//#define CRANK0  ETPU_ENGINE_A_CHANNEL(0)
//#define TOOTHGEN0_CRANK ETPU_ENGINE_A_CHANNEL(5)
//#define TOOTHGEN0_CAM   ETPU_ENGINE_A_CHANNEL(1)
//#define KNOCK_WINDOW0_KNOCK_WINDOW      ETPU_ENGINE_A_CHANNEL(10)
//#define CAM0    ETPU_ENGINE_A_CHANNEL(1)
//#define FUEL0_FUEL_CH_1       ETPU_ENGINE_A_CHANNEL(10)
//#define FUEL0_FUEL_CH_2       ETPU_ENGINE_A_CHANNEL(6)
//#define FUEL0_FUEL_CH_3       ETPU_ENGINE_A_CHANNEL(7)
//#define FUEL0_FUEL_CH_4       ETPU_ENGINE_A_CHANNEL(8)
//#define TOOTHGEN0_CRANK       ETPU_ENGINE_A_CHANNEL(0)
//#define CRANK0        ETPU_ENGINE_A_CHANNEL(5)
//#define TOOTHGEN0_CAM ETPU_ENGINE_A_CHANNEL(14)
//#define CAM0  ETPU_ENGINE_A_CHANNEL(1)
//#define KNOCK_WINDOW0_KNOCK_WINDOW    ETPU_ENGINE_A_CHANNEL(10)

/**************************************************************************
 * Interrupt Enable, DMA Enable and Output Disable options
 * filled accodring to the user settings
 **************************************************************************/
#define ETPU_CIE_A    0x00000000
#define ETPU_DTRE_A   0x00000000
#define ETPU_ODIS_A   0x00000000
#define ETPU_OPOL_A   0x00000000
#define ETPU_CIE_B    0x00000000
#define ETPU_DTRE_B   0x00000000
#define ETPU_ODIS_B   0x00000000
#define ETPU_OPOL_B   0x00000000

/**************************************************************************
 * function prototypes
 **************************************************************************/
int32_t my_system_etpu_init ();
void    my_system_etpu_start();

