
/****************************************************************
 * WARNING this file is automatically generated DO NOT EDIT IT! *
 *                                                              *
 * FILE NAME: etpu_spi_auto.h      COPYRIGHT (c) Freescale 2004 *
 *                                      All Rights Reserved     *
 * This file generated by:                                      *
 * $RCSfile: etpuc_spi.c,v $ $Revision: 1.5 $
 *                                                              *
 * This file provides an interface between eTPU code and CPU    *
 * code. All references to the SPI function should be made with *
 * information in this file. This allows only symbolic          *
 * information to be referenced which allows the eTPU code to be*
 * optimized without effecting the CPU code.                    *
 ****************************************************************/
#ifndef _ETPU_SPI_AUTO_H_
#define _ETPU_SPI_AUTO_H_

/* Function Configuration Information */
#define FS_ETPU_SPI_FUNCTION_NUMBER  8 
#define FS_ETPU_SPI_TABLE_SELECT 1 
#define FS_ETPU_SPI_NUM_PARMS 0x0008 

/* Host Service Request Definitions -timer options*/
#define FS_ETPU_SPI_INIT_TCR1 7  
#define FS_ETPU_SPI_INIT_TCR2 5  

/* Host Service Request Definitions -non init (placed here for GCT compliance)*/
#define FS_ETPU_SPI_RUN 3  

/* Function Mode Bit Definitions - polarity options*/
#define FS_ETPU_SPI_CLK_POL_POS 0  
#define FS_ETPU_SPI_CLK_POL_NEG 1  
/* Function Mode Bit Definitions - shift_dir options*/
#define FS_ETPU_SPI_SHIFT_DIR_MSB 0  
#define FS_ETPU_SPI_SHIFT_DIR_LSB 1  

/* Parameter Definitions */
#define FS_ETPU_SPI_BIT_COUNT  0x0000
#define FS_ETPU_SPI_DATA_REG  0x0001
#define FS_ETPU_SPI_HALF_PERIOD  0x0005

#endif /* _ETPU_SPI_AUTO_H_ */

