
/* WARNING this file is automatically generated DO NOT EDIT IT! */
/*                                                              */
/* This file provides an interface between eTPU code and CPU    */
/* code. All references to the ToothGen function should be made */
/* with information in this file. This allows only symbolic     */
/* information to be referenced which allows the eTPU code to be*/
/* optimized without effecting the CPU code.                    */
/****************************************************************/
#ifndef _ETPU_TOOTHGEN_AUTO_H_
#define _ETPU_TOOTHGEN_AUTO_H_
/****************************************************************
* Function Configuration Information.
****************************************************************/
#define FS_ETPU_TOOTHGEN_FUNCTION_NUMBER    17 
#define FS_ETPU_TOOTHGEN_TABLE_SELECT       1 
#define FS_ETPU_TOOTHGEN_NUM_PARMS          0x0048 

/****************************************************************
* Host Service Request Definitions.
****************************************************************/
#define FS_ETPU_TOOTHGEN_HSR_INIT           7 

/****************************************************************
* TOOTHGEN eTPU Function Parameter Definitions.
****************************************************************/
#define FS_ETPU_TOOTHGEN_TEETHPERREV_OFFSET         0x0001
#define FS_ETPU_TOOTHGEN_TEETHMISSING_OFFSET        0x0000
#define FS_ETPU_TOOTHGEN_TOOTHDUTYCYCLE_OFFSET      0x0005
#define FS_ETPU_TOOTHGEN_TOOTHPERIOD_OFFSET         0x0009
#define FS_ETPU_TOOTHGEN_TOOTHPERIODNEW_OFFSET      0x000D
#define FS_ETPU_TOOTHGEN_ACCELRATE_OFFSET           0x0011
#define FS_ETPU_TOOTHGEN_CAMSTART_OFFSET            0x0015
#define FS_ETPU_TOOTHGEN_CAMSTOP_OFFSET             0x0019
#define FS_ETPU_TOOTHGEN_CAMCHANNEL_OFFSET          0x0004
#define FS_ETPU_TOOTHGEN_TOOTHNUMBER_OFFSET         0x001D
#define FS_ETPU_TOOTHGEN_ERRORSWITCH_OFFSET         0x0008
#define FS_ETPU_TOOTHGEN_MISSINGTOOTH_OFFSET        0x0021
#define FS_ETPU_TOOTHGEN_MISSINGTOOTH2_OFFSET       0x0025
#define FS_ETPU_TOOTHGEN_NOISETOOTH_OFFSET          0x0029
#define FS_ETPU_TOOTHGEN_NOISEPULSESHIFT_OFFSET     0x002D
#define FS_ETPU_TOOTHGEN_NOISEPULSEWIDTH_OFFSET     0x0031
#define FS_ETPU_TOOTHGEN_CAMNOISETOOTH_OFFSET       0x0035
#define FS_ETPU_TOOTHGEN_CAMNOISEPULSESHIFT_OFFSET  0x0039
#define FS_ETPU_TOOTHGEN_CAMNOISEPULSEWIDTH_OFFSET  0x003D

/****************************************************************
* Value Definitions.
****************************************************************/
#define FS_ETPU_TOOTHGEN_FM0_CRANK_CHAN    0 
#define FS_ETPU_TOOTHGEN_FM0_CAM_CHAN      1 

#define FS_ETPU_TOOTHGEN_ERROR_MISSING_HIGHTIME  1 
#define FS_ETPU_TOOTHGEN_ERROR_MISSING_LOWTIME   2  
#define FS_ETPU_TOOTHGEN_ERROR_CRANKNOISE        4       
#define FS_ETPU_TOOTHGEN_ERROR_MISSING_CAM       8      
#define FS_ETPU_TOOTHGEN_ERROR_CAMNOISE          16         
#define FS_ETPU_TOOTHGEN_ERROR_TOOTH_IN_GAP      32     

#endif
