
/****************************************************************
 * WARNING this file is automatically generated DO NOT EDIT IT! *
 *                                                              *
 * FILE NAME: etpu_qom_auto.h      COPYRIGHT (c) Freescale 2004 *
 *                                      All Rights Reserved     *
 * This file generated by:                                      *
 * $RCSfile: etpuc_qom.c,v $ $Revision: 1.5 $
 *                                                           *
 * This file provides an interface between eTPU code and CPU    *
 * code. All references to the QOM function should be made with *
 * information in this file. This allows only symbolic          *
 * information to be referenced which allows the eTPU code to be*
 * optimized without effecting the CPU code.                    *
 ****************************************************************/
#ifndef _ETPU_QOM_AUTO_H_
#define _ETPU_QOM_AUTO_H_

/* Function Configuration Information */
#define FS_ETPU_QOM_FUNCTION_NUMBER  6 
#define FS_ETPU_QOM_TABLE_SELECT 0 
#define FS_ETPU_QOM_NUM_PARMS 0x0018 

/* Time Reference Mode Bits - first_match_mode options */
#define FS_ETPU_QOM_IMMEDIATE 0 
#define FS_ETPU_QOM_USE_LAST_EVENT 1 
#define FS_ETPU_QOM_USE_REF_ADDRESS 3 

/* Host Service Request Definitions - init_pin options */
#define FS_ETPU_QOM_INIT_PIN_LOW_LINK 2  
#define FS_ETPU_QOM_INIT_PIN_HIGH_LINK 3  
#define FS_ETPU_QOM_INIT_PIN_NO_CHANGE_LINK 4  
#define FS_ETPU_QOM_INIT_PIN_LOW 5  
#define FS_ETPU_QOM_INIT_PIN_HIGH 6  
#define FS_ETPU_QOM_INIT_PIN_NO_CHANGE 7  

/* Function Mode Bit Definitions - mode options */
#define FS_ETPU_QOM_SINGLE_SHOT 0  
#define FS_ETPU_QOM_LOOP 1  
#define FS_ETPU_QOM_CONTINUOUS 2  
#define FS_ETPU_QOM_CONTINUOUS_A 3  

/* Parameter Definitions */
#define FS_ETPU_QOM_TABLE_START_PTR_OFFSET  0x0001
#define FS_ETPU_QOM_TABLE_END_PTR_OFFSET  0x0005
#define FS_ETPU_QOM_LAST_MATCH_TIME_OFFSET  0x0009
#define FS_ETPU_QOM_LOOP_COUNT_OFFSET  0x0000
#define FS_ETPU_QOM_OPTION_OFFSET  0x0004
#define FS_ETPU_QOM_REF_ADDR_PTR_OFFSET  0x000D

#endif /* _ETPU_QOM_AUTO_H_ */

