
/****************************************************************
 * WARNING this file is automatically generated DO NOT EDIT IT! *
 *                                                              *
 * FILE NAME: etpu_pwm_auto.h      COPYRIGHT (c) Freescale 2004 *
 *                                      All Rights Reserved     *
 * This file generated by:                                      *
 * $RCSfile: etpuc_pwm.c,v $ $Revision: 1.8 $
 *                                                              *
 * This file provides an interface between eTPU code and CPU    *
 * code. All references to the PWM function should be made with *
 * information in this file. This allows only symbolic          *
 * information to be referenced which allows the eTPU code to be*
 * optimized without effecting the CPU code.                    *
 ****************************************************************/
#ifndef _ETPU_PWM_AUTO_H_
#define _ETPU_PWM_AUTO_H_

/* Function Configuration Information */
#define FS_ETPU_PWM_FUNCTION_NUMBER  1 
#define FS_ETPU_PWM_TABLE_SELECT 1 
#define FS_ETPU_PWM_NUM_PARMS 0x0018 

/* Host Service Request Definitions */
#define FS_ETPU_PWM_INIT 7 
#define FS_ETPU_PWM_IMM_UPDATE 3 
#define FS_ETPU_PWM_CO_UPDATE 5 

/* Function Mode Bit Definitions - polarity options */
#define FS_ETPU_PWM_ACTIVEHIGH 1  
#define FS_ETPU_PWM_ACTIVELOW 0   

/* Parameter Definitions */
#define FS_ETPU_PWM_PERIOD_OFFSET  0x0001
#define FS_ETPU_PWM_ACTIVE_OFFSET  0x0005
#define FS_ETPU_PWM_CO_PERIOD_OFFSET  0x0009
#define FS_ETPU_PWM_CO_ACTIVE_OFFSET  0x000D

#endif /* _ETPU_PWM_AUTO_H_ */

