
/****************************************************************/
/* WARNING this file is automatically generated DO NOT EDIT IT! */
/*                                                              */
/* This file provides an interface between eTPU code and CPU    */
/* code. All references to the FUEL function should be made     */
/* with information in this file. This allows only symbolic     */
/* information to be referenced which allows the eTPU code to be*/
/* optimized without effecting the CPU code.                    */
/****************************************************************/
#ifndef _ETPU_FUEL_AUTO_H_
#define _ETPU_FUEL_AUTO_H_

/****************************************************************
* Function Configuration Information.
****************************************************************/
#define FS_ETPU_FUEL_FUNCTION_NUMBER  14 
#define FS_ETPU_FUEL_TABLE_SELECT    1 
#define FS_ETPU_FUEL_NUM_PARMS       0x0020 

/****************************************************************
* Host Service Request Definitions.
****************************************************************/
#define FS_ETPU_FUEL_INIT                  7 
#define FS_ETPU_FUEL_INJECTION_TIME_CHANGE 3

/****************************************************************
* Global Parameter Definitions.
****************************************************************/
#define FS_ETPU_FUEL_DROP_DEAD_ANGLE_OFFSET                0x0009
#define FS_ETPU_FUEL_INJECTION_NORMAL_END_ANGLE_OFFSET     0x000D
#define FS_ETPU_FUEL_COMPENSATION_TIME_OFFSET              0x0011
#define FS_ETPU_FUEL_MINIMUM_INJECTION_TIME_OFFSET         0x0015
#define FS_ETPU_FUEL_MINIMUM_OFF_TIME_OFFSET               0x0019
#define FS_ETPU_FUEL_SUM_OF_INJECTION_TIME_OFFSET          0x001D
#define FS_ETPU_FUEL_RECALCULATION_OFFSET_ANGLE_OFFSET     0x0021

/****************************************************************
* Channel Parameter Definitions.
****************************************************************/
#define FS_ETPU_FUEL_CYLINDER_OFFSET_ANGLE_OFFSET          0x0001
#define FS_ETPU_FUEL_INJECTION_START_ANGLE_OFFSET          0x0005
#define FS_ETPU_FUEL_INJECTION_TIME_OFFSET                 0x0009
#define FS_ETPU_FUEL_REAL_INJECTION_TIME_OFFSET            0x000D
#define FS_ETPU_FUEL_TCR2_COUNTS_PER_ENGINE_CYCLE_OFFSET   0x0011
#define FS_ETPU_FUEL_CPU_REAL_INJECTION_TIME_OFFSET        0x0015

/* fuel polarity options */
#define FS_ETPU_FUEL_FM0_ACTIVE_HIGH  1 
#define FS_ETPU_FUEL_FM0_ACTIVE_LOW   0  

/* switching off options */
#define FS_ETPU_FUEL_FM1_PULSE_GENERATION_ALLOWED  0 
#define FS_ETPU_FUEL_FM1_PULSE_GENERATION_DISABLED 1 

#endif
