
/****************************************************************/
/* WARNING this file is automatically generated DO NOT EDIT IT! */
/*                                                              */
/* This file provides an interface between eTPU code and CPU    */
/* code.  All references to the SPARK function should be made   */
/* with information in this file.  This allows only symbolic    */
/* information to be referenced which allows the eTPU code to   */
/* be optimized without affecting the CPU code.                 */
/****************************************************************/
#ifndef _ETPU_SPARK_AUTO_H_
#define _ETPU_SPARK_AUTO_H_

/****************************************************************
* Function Configuration Information.
****************************************************************/
#define FS_ETPU_SPARK_FUNCTION_NUMBER  15 
#define FS_ETPU_SPARK_TABLE_SELECT     1 
#define FS_ETPU_SPARK_NUM_PARMS        0x0028 

/****************************************************************
* Host Service Request Definitions.
****************************************************************/
#define FS_ETPU_SPARK_INIT    7 
#define FS_ETPU_SPARK_UPDATE  3

/****************************************************************
* Global Parameter Definitions.
****************************************************************/
#define FS_ETPU_SPARK_MIN_DWELL_OFFSET                     0x0025
#define FS_ETPU_SPARK_MAX_DWELL_OFFSET                     0x0029
#define FS_ETPU_SPARK_MULTI_ON_TIME_OFFSET                 0x002D
#define FS_ETPU_SPARK_MULTI_OFF_TIME_OFFSET                0x0031
#define FS_ETPU_SPARK_MULTI_NUM_PULSES_OFFSET              0x0000
#define FS_ETPU_SPARK_RECALC_OFFSET_ANGLE_OFFSET           0x0035
#define FS_ETPU_SPARK_TCR2_COUNTS_PER_ENGINE_CYCLE_OFFSET  0x0039

/****************************************************************
* Channel Parameter Definitions.
****************************************************************/
#define FS_ETPU_SPARK_SPARK1_ANGLE_OFFSET                  0x0001
#define FS_ETPU_SPARK_SPARK1_DWELL_OFFSET                  0x0005
#define FS_ETPU_SPARK_SPARK2_ANGLE_OFFSET                  0x0009
#define FS_ETPU_SPARK_SPARK2_DWELL_OFFSET                  0x000D
#define FS_ETPU_SPARK_CYLINDER_OFFSET_ANGLE_OFFSET         0x0011

/* SPARK output polarity options */
#define FS_ETPU_SPARK_FM0_ACTIVE_LOW   0  
#define FS_ETPU_SPARK_FM0_ACTIVE_HIGH  1 

#endif
