
/****************************************************************
 * WARNING this file is automatically generated DO NOT EDIT IT! *
 *                                                              *
 * FILE NAME: etpu_ic_auto.h       COPYRIGHT (c) Freescale 2004 *
 *                                      All Rights Reserved     *
 * This file generated by:                                      *
 * $RCSfile: etpuc_ic.c,v $ $Revision: 1.7 $
 *                                                              *
 * This file provides an interface between eTPU code and CPU    *
 * code. All references to the IC function should be made with  *
 * information in this file. This allows only symbolic          *
 * information to be referenced which allows the eTPU code to be*
 * optimized without effecting the CPU code.                    *
 ****************************************************************/
#ifndef _ETPU_IC_AUTO_H_
#define _ETPU_IC_AUTO_H_

/* Function Configuration Information */
#define ETPU_IC_FUNCTION_NUMBER  2 
#define ETPU_IC_TABLE_SELECT 0 
#define ETPU_IC_NUM_PARMS 0x0020 

/* Host Service Request Definitions */
#define ETPU_IC_INIT_TCR1 7 
#define ETPU_IC_INIT_TCR2 6 
#define ETPU_IC_INIT_PRAM 5 

/* Function Mode Definitions - mode options*/
#define ETPU_IC_MODE_SINGLE 1 
#define ETPU_IC_MODE_CONT 0 
#define ETPU_IC_MODE_LINK (1  << 1)

/* Parameter Definitions */
#define ETPU_IC_FLAGS_OFFSET  0x0000
#define ETPU_IC_MAXCOUNT_OFFSET  0x0001
#define ETPU_IC_TRANSCOUNT_OFFSET  0x0005
#define ETPU_IC_FINAL_OFFSET  0x0009
#define ETPU_IC_LAST_OFFSET  0x000D
#define ETPU_IC_ADDRESS_OFFSET  0x0011
#define ETPU_IC_LINK1_OFFSET  0x0014
#define ETPU_IC_LINK2_OFFSET  0x0018

/* Flag Parameter Definitions - edge options*/
#define ETPU_IC_FALLING_EDGE 0
#define ETPU_IC_RISING_EDGE 1
#define ETPU_IC_ANY_EDGE 2

#endif /* _ETPU_IC_AUTO_H_ */

