
/****************************************************************/
/* WARNING this file is automatically generated DO NOT EDIT IT! */
/*                                                              */
/* This file provides an interface between eTPU code and CPU    */
/* code. All references to the KNOCK function should be made    */
/* with information in this file. This allows only symbolic     */
/* information to be referenced which allows the eTPU code to be*/
/* optimized without effecting the CPU code.                    */
/****************************************************************/
#ifndef _ETPU_KNOCK_AUTO_H_
#define _ETPU_KNOCK_AUTO_H_

/****************************************************************
* Function Configuration Information.
****************************************************************/
#define FS_ETPU_KNOCK_WINDOW_FUNCTION_NUMBER  16 
#define FS_ETPU_KNOCK_WINDOW_TABLE_SELECT    0 
#define FS_ETPU_KNOCK_WINDOW_NUM_PARMS       0x0018 

/****************************************************************
/* Host Service Request Definitions */
/****************************************************************/
#define FS_ETPU_KNOCK_INIT       			 7 

/****************************************************************
/* Parameter Definitions */
/****************************************************************/
#define FS_ETPU_KNOCK_NUMBER_OF_WINDOWS_OFFSET               0x0000
#define FS_ETPU_KNOCK_TCR2_COUNTS_PER_ENGINE_CYCLE_OFFSET	   0x0001
#define FS_ETPU_KNOCK_TABLE_START_PTR_OFFSET     					   0x0005

/* edge_polarity options */
#define FS_ETPU_KNOCK_FM0_RISING_EDGE 1 
#define FS_ETPU_KNOCK_FM0_FALLING_EDGE 0 
/* edge_interrupt options */
#define FS_ETPU_KNOCK_FM1_INT_OPEN (1 <<1)
#define FS_ETPU_KNOCK_FM1_INT_CLOSE (0 <<1)

#endif /* _ETPU_KNOCK_AUTO_H_ */

